# -*- shell-script -*-

# ------------------------------------------------------------------------------
# Behaviour
# ------------------------------------------------------------------------------
## History
export HISTIGNORE="&:ls:cd:[bf]g:rm *:rm -rf *:rm -f *:exit"

## Disable $ escaping
shopt -s direxpand

# ------------------------------------------------------------------------------
# Exports
# ------------------------------------------------------------------------------

## Editors
export EDITOR="emacs --no-window-system"

## Language
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

## PS1
# Git
GIT_PS1_SHOWDIRTYSTATE='y'
GIT_PS1_SHOWSTASHSTATE='y'
GIT_PS1_SHOWUNTRACKEDFILES='y'
GIT_PS1_DESCRIBE_STYLE='contains'
GIT_PS1_SHOWUPSTREAM='auto'

PS1='\[\033[01;34m\][\[\033[01;35m\]\u@\h\[\033[01;34m\] \W]$(__git_ps1 "\[\033[01;34m\][\[\033[01;33m\]%s\[\033[01;34m\]]")[\[\033[01;31m\]\j\[\033[01;34m\]]\$\[\033[00m\] '

## PATH
export PATH="${HOME}/bin:${USER_DIR}/bin:${PATH}"

# ------------------------------------------------------------------------------
# Aliases
# ------------------------------------------------------------------------------

# Git
alias gst='git status'
alias gbr='git checkout -b'
alias gdi='git diff'
alias gp="git stash; git pull; git pop"

# bashrc
alias vibashrc="emacs ${USER_DIR}/conf/_bashrc && . ${HOME}/.bashrc"

# Better defaults
alias emacs='emacs --no-window-system'
alias rm='rm -i'
alias grep='grep --color'
alias ls='ls --color=auto'
alias dmesg='dmesg --human --nopager'
alias diff='diff -wu --color'
alias jq='jq -C'

# Docker
alias dk=docker
alias dktail='docker logs -n 10 -f'

# Utils
alias trash='\rm -vf *~ .??*~; true'

mkcd() {
  mkdir -p "$1" && cd "$1"
}

tssh() {
  tmux new-window -n "$1" ssh "$1"
}


# ------------------------------------------------------------------------------
# Local config
# ------------------------------------------------------------------------------
[[ -f "$USER_DIR/opt/bashrc" ]] && . "$USER_DIR/opt/bashrc"
